name: Deploy to Production

on:
  push:
    branches:
      - main  # o la rama principal que estÃ©s usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }} # O usa una key si prefieres
          port: 22
          script: |
            echo "ğŸ“ Entrando a la carpeta del proyecto"
            cd /var/www/upqroo-bolsa-empleo

            echo "ğŸ“Œ Haciendo pull del repositorio"
            git pull origin main

            echo "ğŸ“¦ Instalando dependencias"
            npm install

            echo "ğŸ› ï¸ Ejecutando build"
            npm run build

            echo "ğŸ”„ Reiniciando PM2"
            pm2 restart 0

            echo "âœ… Deploy completado"
